In [1]:
import os
import numpy as np
import pandas as pd

from scipy.stats import pearsonr
import pymannkendall as mk

In [2]:
PROJECT = r"C:\Users\ACER\OneDrive\Desktop\ISRO\snow_2"

MASTER_DATASET = os.path.join(
    PROJECT,
    "Master_dataset"
)

RESULTS = os.path.join(
    PROJECT,
    "Results"
)

In [3]:
SEAICE_FILE = os.path.join(
    MASTER_DATASET,
    "Yearly_Average_Sea_Ice.xlsx"
)

ALBEDO_FILE = os.path.join(
    MASTER_DATASET,
    "Albedo_Statistics_2000_2026 (1).xlsx"
)

seaice = pd.read_excel(SEAICE_FILE)

albedo = pd.read_excel(
    ALBEDO_FILE,
    sheet_name="Yearly_albedo_statistics"
)

print(seaice.head())

print(albedo.head())

   Year   March   April     May    June   July  August  September  \
0  2000  12.827  12.781  12.217  11.168  9.518   7.251      6.361
1  2001  13.032  12.991  12.403  11.224  9.281   7.526      6.778
2  2002  12.957  12.663  12.112  11.088  9.358   6.565      5.981
3  2003  12.960  12.805  12.157  11.286  9.386   6.931      6.184
4  2004  12.914  12.615  11.778  10.991  9.297   6.834      6.082

   Yearly Mean  Minimum  Maximum  Standard Deviation
0       10.303    6.361   12.827               2.658
1       10.462    6.778   13.032               2.612
2       10.103    5.981   12.957               2.880
3       10.244    6.184   12.960               2.795
4       10.073    6.082   12.914               2.748
   Year  Ocean Mean Albedo  Land Mean Albedo  Overall Mean Albedo
0  2000             0.4890            0.3916               0.4541
1  2001             0.4980            0.3917               0.4599
2  2002             0.4835            0.3865               0.4487
3  2003             0.4770            0.3764               0.4409
4  2004             0.4933            0.3953               0.4582

In [4]:
# ============================================================
# CREATE MASTER DATASET
# ============================================================

df = pd.merge(
    seaice,
    albedo,
    on="Year",
    how="inner"
)

print(df.head())

print()

print(df.shape)

print()

print(df.columns.tolist())

   Year   March   April     May    June   July  August  September  \
0  2000  12.827  12.781  12.217  11.168  9.518   7.251      6.361
1  2001  13.032  12.991  12.403  11.224  9.281   7.526      6.778
2  2002  12.957  12.663  12.112  11.088  9.358   6.565      5.981
3  2003  12.960  12.805  12.157  11.286  9.386   6.931      6.184
4  2004  12.914  12.615  11.778  10.991  9.297   6.834      6.082

   Yearly Mean  Minimum  Maximum  Standard Deviation  Ocean Mean Albedo  \
0       10.303    6.361   12.827               2.658             0.4890
1       10.462    6.778   13.032               2.612             0.4980
2       10.103    5.981   12.957               2.880             0.4835
3       10.244    6.184   12.960               2.795             0.4770
4       10.073    6.082   12.914               2.748             0.4933

   Land Mean Albedo  Overall Mean Albedo
0            0.3916               0.4541
1            0.3917               0.4599
2            0.3865               0.4487
3            0.3764               0.4409
4            0.3953               0.4582

(26, 15)

['Year', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'Yearly Mean', 'Minimum', 'Maximum', 'Standard Deviation', 'Ocean Mean Albedo', 'Land Mean Albedo', 'Overall Mean Albedo']

In [5]:
# ============================================================
# LONG-TERM MEANS
# ============================================================

sea_long_mean = df["Yearly Mean"].mean()

albedo_long_mean = df["Ocean Mean Albedo"].mean()

print(f"Sea Ice Long-Term Mean      : {sea_long_mean:.4f}")

print(f"Ocean Albedo Long-Term Mean : {albedo_long_mean:.4f}")

Sea Ice Long-Term Mean      : 9.6143
Ocean Albedo Long-Term Mean : 0.4577

In [6]:
# ============================================================
# PERCENTAGE DEVIATIONS
# ============================================================

df["Sea Ice Deviation (%)"] = (
    (df["Yearly Mean"] - sea_long_mean)
    / sea_long_mean
) * 100

df["Albedo Deviation (%)"] = (
    (df["Ocean Mean Albedo"] - albedo_long_mean)
    / albedo_long_mean
) * 100

In [7]:
print(df.head())

print()

print(df.shape)

print()

print(df.columns.tolist())

   Year   March   April     May    June   July  August  September  \
0  2000  12.827  12.781  12.217  11.168  9.518   7.251      6.361
1  2001  13.032  12.991  12.403  11.224  9.281   7.526      6.778
2  2002  12.957  12.663  12.112  11.088  9.358   6.565      5.981
3  2003  12.960  12.805  12.157  11.286  9.386   6.931      6.184
4  2004  12.914  12.615  11.778  10.991  9.297   6.834      6.082

   Yearly Mean  Minimum  Maximum  Standard Deviation  Ocean Mean Albedo  \
0       10.303    6.361   12.827               2.658             0.4890
1       10.462    6.778   13.032               2.612             0.4980
2       10.103    5.981   12.957               2.880             0.4835
3       10.244    6.184   12.960               2.795             0.4770
4       10.073    6.082   12.914               2.748             0.4933

   Land Mean Albedo  Overall Mean Albedo  Sea Ice Deviation (%)  \
0            0.3916               0.4541               7.163631
1            0.3917               0.4599               8.817423
2            0.3865               0.4487               5.083390
3            0.3764               0.4409               6.549960
4            0.3953               0.4582               4.771353

   Albedo Deviation (%)
0              6.834052
1              8.800323
2              5.632442
3              4.212357
4              7.773492

(26, 17)

['Year', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'Yearly Mean', 'Minimum', 'Maximum', 'Standard Deviation', 'Ocean Mean Albedo', 'Land Mean Albedo', 'Overall Mean Albedo', 'Sea Ice Deviation (%)', 'Albedo Deviation (%)']

In [8]:
# ============================================================
# DESCRIPTIVE STATISTICS
# ============================================================

descriptive_df = pd.DataFrame({

    "Statistic":[
        "Count",
        "Mean",
        "Median",
        "Standard Deviation",
        "Variance",
        "Minimum",
        "25th Percentile (Q1)",
        "75th Percentile (Q3)",
        "Interquartile Range (IQR)",
        "Maximum",
        "Range"
    ],

    "Sea Ice (Million km²)":[

        df["Yearly Mean"].count(),

        df["Yearly Mean"].mean(),

        df["Yearly Mean"].median(),

        df["Yearly Mean"].std(),

        df["Yearly Mean"].var(),

        df["Yearly Mean"].min(),

        df["Yearly Mean"].quantile(0.25),

        df["Yearly Mean"].quantile(0.75),

        df["Yearly Mean"].quantile(0.75) -
        df["Yearly Mean"].quantile(0.25),

        df["Yearly Mean"].max(),

        df["Yearly Mean"].max() -
        df["Yearly Mean"].min()

    ],

    "Ocean Mean Albedo":[

        df["Ocean Mean Albedo"].count(),

        df["Ocean Mean Albedo"].mean(),

        df["Ocean Mean Albedo"].median(),

        df["Ocean Mean Albedo"].std(),

        df["Ocean Mean Albedo"].var(),

        df["Ocean Mean Albedo"].min(),

        df["Ocean Mean Albedo"].quantile(0.25),

        df["Ocean Mean Albedo"].quantile(0.75),

        df["Ocean Mean Albedo"].quantile(0.75) -
        df["Ocean Mean Albedo"].quantile(0.25),

        df["Ocean Mean Albedo"].max(),

        df["Ocean Mean Albedo"].max() -
        df["Ocean Mean Albedo"].min()

    ]

})

descriptive_df

                    Statistic  Sea Ice (Million km²)  Ocean Mean Albedo
0                       Count              26.000000          26.000000
1                        Mean               9.614269           0.457719
2                      Median               9.557000           0.452900
3          Standard Deviation               0.391553           0.019878
4                    Variance               0.153314           0.000395
5                     Minimum               9.042000           0.428200
6        25th Percentile (Q1)               9.354500           0.444350
7        75th Percentile (Q3)               9.835000           0.474150
8   Interquartile Range (IQR)               0.480500           0.029800
9                     Maximum              10.462000           0.498000
10                      Range               1.420000           0.069800

In [9]:
# ============================================================
# PEARSON CORRELATION
# ============================================================

from scipy.stats import pearsonr

r, p = pearsonr(
    df["Sea Ice Deviation (%)"],
    df["Albedo Deviation (%)"]
)

print("="*50)
print("PEARSON CORRELATION")
print("="*50)

print(f"Correlation Coefficient (r) : {r:.6f}")
print(f"P-value                    : {p:.6f}")

==================================================
PEARSON CORRELATION
==================================================
Correlation Coefficient (r) : 0.937223
P-value                    : 0.000000

In [10]:
# ============================================================
# RELATIONSHIP STRENGTH
# ============================================================

if abs(r) >= 0.90:
    relationship = "Very Strong"
elif abs(r) >= 0.70:
    relationship = "Strong"
elif abs(r) >= 0.50:
    relationship = "Moderate"
elif abs(r) >= 0.30:
    relationship = "Weak"
else:
    relationship = "Very Weak"

direction = "Positive" if r > 0 else "Negative"

print(f"Relationship : {relationship} {direction}")

Relationship : Very Strong Positive

In [11]:
# ============================================================
# PEARSON CORRELATION TABLE
# ============================================================

correlation_df = pd.DataFrame({

    "Variable 1":[
        "Sea Ice Deviation (%)"
    ],

    "Variable 2":[
        "Ocean Mean Albedo Deviation (%)"
    ],

    "Pearson Correlation (r)":[
        r
    ],

    "P-value":[
        p
    ],

    "Relationship":[
        f"{relationship} {direction}"
    ],

    "Interpretation":[
        "Statistically Significant" if p < 0.05
        else "Not Statistically Significant"
    ]

})

correlation_df

,Variable 1,Variable 2,Pearson Correlation (r),P-value,Relationship,Interpretation
0,Sea Ice Deviation (%),Ocean Mean Albedo Deviation (%),0.937223,1.790218e-12,Very Strong Positive,Statistically Significant

In [12]:
# ============================================================
# MANN-KENDALL TEST
# ============================================================

import pymannkendall as mk

sea_result = mk.original_test(
    df["Sea Ice Deviation (%)"]
)

alb_result = mk.original_test(
    df["Albedo Deviation (%)"]
)

In [13]:
# ============================================================
# MANN-KENDALL RESULTS TABLE
# ============================================================

mk_df = pd.DataFrame({

    "Variable":[
        "Sea Ice",
        "Ocean Mean Albedo"
    ],

    "Trend":[
        sea_result.trend,
        alb_result.trend
    ],

    "Significant (H)":[
        sea_result.h,
        alb_result.h
    ],

    "P-value":[
        sea_result.p,
        alb_result.p
    ],

    "Z Statistic":[
        sea_result.z,
        alb_result.z
    ],

    "Kendall Tau":[
        sea_result.Tau,
        alb_result.Tau
    ],

    "S Statistic":[
        sea_result.s,
        alb_result.s
    ],

    "Variance(S)":[
        sea_result.var_s,
        alb_result.var_s
    ],

    "Sen's Slope (%/year)":[
        sea_result.slope,
        alb_result.slope
    ],

    "Intercept":[
        sea_result.intercept,
        alb_result.intercept
    ]

})

mk_df

,Variable,Trend,Significant (H),P-value,Z Statistic,Kendall Tau,S Statistic,Variance(S),Sen's Slope (%/year),Intercept
0,Sea Ice,decreasing,True,0.000066,-3.990490,-0.560000,-182.0,2057.333333,-0.436355,4.858773
1,Ocean Mean Albedo,decreasing,True,0.000114,-3.858209,-0.541538,-176.0,2057.333333,-0.420563,4.204164

In [14]:
# ============================================================
# TREND STATISTICS SUMMARY
# ============================================================

trend_df = pd.DataFrame({

    "Parameter":[

        "Long-Term Mean",

        "Mean Deviation (%)",

        "Maximum Deviation (%)",

        "Minimum Deviation (%)",

        "Sen's Slope (%/year)",

        "Kendall Tau",

        "P-value",

        "Trend",

        "Significant"

    ],

    "Sea Ice":[

        df["Yearly Mean"].mean(),

        df["Sea Ice Deviation (%)"].mean(),

        df["Sea Ice Deviation (%)"].max(),

        df["Sea Ice Deviation (%)"].min(),

        sea_result.slope,

        sea_result.Tau,

        sea_result.p,

        sea_result.trend,

        sea_result.h

    ],

    "Ocean Mean Albedo":[

        df["Ocean Mean Albedo"].mean(),

        df["Albedo Deviation (%)"].mean(),

        df["Albedo Deviation (%)"].max(),

        df["Albedo Deviation (%)"].min(),

        alb_result.slope,

        alb_result.Tau,

        alb_result.p,

        alb_result.trend,

        alb_result.h

    ]

})

trend_df

               Parameter     Sea Ice Ocean Mean Albedo
0         Long-Term Mean    9.614269          0.457719
1     Mean Deviation (%)        -0.0               0.0
2  Maximum Deviation (%)    8.817423          8.800323
3  Minimum Deviation (%)    -5.95229           -6.4492
4   Sen's Slope (%/year)   -0.436355         -0.420563
5            Kendall Tau       -0.56         -0.541538
6                P-value    0.000066          0.000114
7                  Trend  decreasing        decreasing
8            Significant        True              True

In [15]:
# ============================================================
# EXPORT FINAL EXCEL WORKBOOK
# ============================================================

OUTPUT_FILE = os.path.join(
    RESULTS,
    "Arctic_SeaIce_Albedo_Trend_Analysis_2000_2025.xlsx"
)

with pd.ExcelWriter(
    OUTPUT_FILE,
    engine="openpyxl"
) as writer:

    # ========================================================
    # Sheet 1
    # ========================================================
    df.to_excel(
        writer,
        sheet_name="01_Master_Dataset",
        index=False
    )

    # ========================================================
    # Sheet 2
    # ========================================================
    descriptive_df.to_excel(
        writer,
        sheet_name="02_Descriptive_Statistics",
        index=False
    )

    # ========================================================
    # Sheet 3
    # ========================================================
    correlation_df.to_excel(
        writer,
        sheet_name="03_Pearson_Correlation",
        index=False
    )

    # ========================================================
    # Sheet 4
    # ========================================================
    mk_df.to_excel(
        writer,
        sheet_name="04_Mann_Kendall_Test",
        index=False
    )

    # ========================================================
    # Sheet 5
    # ========================================================
    trend_df.to_excel(
        writer,
        sheet_name="05_Trend_Summary",
        index=False
    )

print("="*70)
print("Arctic Sea Ice & Albedo Trend Analysis Workbook Created Successfully")
print("="*70)
print(f"\nSaved at:\n{OUTPUT_FILE}")

======================================================================
Arctic Sea Ice & Albedo Trend Analysis Workbook Created Successfully
======================================================================

Saved at:
C:\Users\ACER\OneDrive\Desktop\ISRO\snow_2\Results\Arctic_SeaIce_Albedo_Trend_Analysis_2000_2025.xlsx

In [16]:
# ============================================================
# ANNUAL STATISTICS
# ============================================================

annual_df = df[[
    "Year",
    "Yearly Mean",
    "Ocean Mean Albedo",
    "Sea Ice Deviation (%)",
    "Albedo Deviation (%)"
]].copy()

annual_df.rename(columns={

    "Yearly Mean":"Sea Ice Area (Million km²)"

}, inplace=True)

annual_df

,Year,Sea Ice Area (Million km²),Ocean Mean Albedo,Sea Ice Deviation (%),Albedo Deviation (%)
0,2000,10.303,0.4890,7.163631,6.834052
1,2001,10.462,0.4980,8.817423,8.800323
2,2002,10.103,0.4835,5.083390,5.632442
3,2003,10.244,0.4770,6.549960,4.212357
4,2004,10.073,0.4933,4.771353,7.773492
5,2005,9.895,0.4768,2.919939,4.168662
6,2006,9.805,0.4823,1.983830,5.370272
7,2007,9.349,0.4481,-2.759120,-2.101557
8,2008,9.703,0.4574,0.922907,-0.069744
9,2009,9.845,0.4662,2.399878,1.852832
10,2010,9.622,0.4483,0.080409,-2.057862
11,2011,9.406,0.4380,-2.166251,-4.308150
12,2012,9.109,0.4304,-5.255410,-5.968556
13,2013,9.753,0.4639,1.442967,1.350341
14,2014,9.629,0.4586,0.153218,0.192426
15,2015,9.406,0.4438,-2.166251,-3.040998
16,2016,9.115,0.4355,-5.193002,-4.854336
17,2017,9.371,0.4531,-2.530294,-1.009184
18,2018,9.299,0.4527,-3.279180,-1.096574
19,2019,9.042,0.4379,-5.952290,-4.329997
20,2020,9.092,0.4282,-5.432230,-6.449200
21,2021,9.422,0.4460,-1.999832,-2.560354
22,2022,9.665,0.4551,0.527661,-0.572235
23,2023,9.492,0.4481,-1.271748,-2.101557
24,2024,9.473,0.4427,-1.469370,-3.281320
25,2025,9.293,0.4468,-3.341588,-2.385574

In [17]:
methodology_df = pd.DataFrame({

    "Step":[

        "Sea Ice Long-Term Mean",

        "Ocean Albedo Long-Term Mean",

        "Sea Ice Deviation",

        "Albedo Deviation",

        "Pearson Correlation",

        "Mann-Kendall Test",

        "Sen's Slope"

    ],

    "Description":[

        "Average of yearly mean sea ice from 2000-2025",

        "Average of yearly ocean mean albedo from 2000-2025",

        "(Yearly Mean - Long-Term Mean)/Long-Term Mean ×100",

        "(Ocean Mean Albedo - Long-Term Mean)/Long-Term Mean ×100",

        "Measures linear relationship between sea ice and albedo",

        "Detects statistically significant monotonic trend",

        "Median annual rate of change"

    ]

})

methodology_df

,Step,Description
0,Sea Ice Long-Term Mean,Average of yearly mean sea ice from 2000-2025
1,Ocean Albedo Long-Term Mean,Average of yearly ocean mean albedo from 2000-...
2,Sea Ice Deviation,(Yearly Mean - Long-Term Mean)/Long-Term Mean ...
3,Albedo Deviation,(Ocean Mean Albedo - Long-Term Mean)/Long-Term...
4,Pearson Correlation,Measures linear relationship between sea ice a...
5,Mann-Kendall Test,Detects statistically significant monotonic trend
6,Sen's Slope,Median annual rate of change

In [18]:
metadata_df = pd.DataFrame({

    "Parameter":[

        "Study Region",

        "Study Period",

        "Total Years",

        "Months Used",

        "Sea Ice Unit",

        "Albedo Unit",

        "Trend Test",

        "Correlation Method",

        "Software",

        "Programming Language"

    ],

    "Value":[

        "Arctic",

        "2000-2025",

        len(df),

        "March-September",

        "Million km²",

        "Unitless",

        "Mann-Kendall",

        "Pearson",

        "Python",

        "Python 3"

    ]

})

metadata_df

              Parameter            Value
0          Study Region           Arctic
1          Study Period        2000-2025
2           Total Years               26
3           Months Used  March-September
4          Sea Ice Unit      Million km²
5           Albedo Unit         Unitless
6            Trend Test     Mann-Kendall
7    Correlation Method          Pearson
8              Software           Python
9  Programming Language         Python 3

In [19]:
# ========================================================
# Sheet 6
# ========================================================

annual_df.to_excel(
    writer,
    sheet_name="06_Annual_Statistics",
    index=False
)

# ========================================================
# Sheet 7
# ========================================================

methodology_df.to_excel(
    writer,
    sheet_name="07_Methodology",
    index=False
)

# ========================================================
# Sheet 8
# ========================================================

metadata_df.to_excel(
    writer,
    sheet_name="08_Metadata",
    index=False
)

In [20]:
# ============================================================
# METADATA
# ============================================================

metadata_df = pd.DataFrame({

    "Parameter":[

        "Project Title",

        "Study Region",

        "Study Period",

        "Total Years",

        "Temporal Resolution",

        "Months Used",

        "Sea Ice Source File",

        "Albedo Source File",

        "Albedo Source Sheet",

        "Number of Observations",

        "Sea Ice Variable",

        "Ocean Albedo Variable",

        "Sea Ice Unit",

        "Albedo Unit",

        "Trend Test",

        "Correlation Method",

        "Programming Language",

        "Software"

    ],

    "Value":[

        "Arctic Sea Ice and Ocean Mean Albedo Trend Analysis",

        "Arctic Ocean",

        "2000–2025",

        26,

        "Annual",

        "March–September",

        "Yearly_Average_Sea_Ice.xlsx",

        "Albedo_Statistics_2000_2026 (1).xlsx",

        "Yearly_albedo_statistics",

        len(df),

        "Yearly Mean Sea Ice Area",

        "Ocean Mean Albedo",

        "Million km²",

        "Unitless",

        "Mann–Kendall Test with Sen's Slope",

        "Pearson Correlation",

        "Python 3",

        "Jupyter Notebook"

    ]

})

metadata_df

                 Parameter                                              Value
0            Project Title  Arctic Sea Ice and Ocean Mean Albedo Trend Ana...
1             Study Region                                       Arctic Ocean
2             Study Period                                          2000–2025
3              Total Years                                                 26
4      Temporal Resolution                                             Annual
5              Months Used                                    March–September
6      Sea Ice Source File                        Yearly_Average_Sea_Ice.xlsx
7       Albedo Source File               Albedo_Statistics_2000_2026 (1).xlsx
8      Albedo Source Sheet                           Yearly_albedo_statistics
9   Number of Observations                                                 26
10        Sea Ice Variable                           Yearly Mean Sea Ice Area
11   Ocean Albedo Variable                                  Ocean Mean Albedo
12            Sea Ice Unit                                        Million km²
13             Albedo Unit                                           Unitless
14              Trend Test                 Mann–Kendall Test with Sen's Slope
15      Correlation Method                                Pearson Correlation
16    Programming Language                                           Python 3
17                Software                                   Jupyter Notebook

In [21]:
about_df = pd.DataFrame({

    "Field":[
        "Project Title",
        "Study Region",
        "Study Period",
        "Temporal Resolution",
        "Months Included",
        "Variables Analysed",
        "Statistical Tests",
        "Programming Language",
        "Software",
        "Workbook Version"
    ],

    "Information":[

        "Arctic Sea Ice and Ocean Mean Albedo Trend Analysis",

        "Arctic Ocean",

        "2000–2025",

        "Annual",

        "March–September",

        "Sea Ice Area, Ocean Mean Albedo",

        "Pearson Correlation, Mann-Kendall Test, Sen's Slope",

        "Python",

        "Jupyter Notebook",

        "1.0"

    ]

})

about_df

                  Field                                        Information
0         Project Title  Arctic Sea Ice and Ocean Mean Albedo Trend Ana...
1          Study Region                                       Arctic Ocean
2          Study Period                                          2000–2025
3   Temporal Resolution                                             Annual
4       Months Included                                    March–September
5    Variables Analysed                    Sea Ice Area, Ocean Mean Albedo
6     Statistical Tests  Pearson Correlation, Mann-Kendall Test, Sen's ...
7  Programming Language                                             Python
8              Software                                   Jupyter Notebook
9      Workbook Version                                                1.0

In [22]:
about_df.to_excel(
    writer,
    sheet_name="00_About_Workbook",
    index=False
)

In [23]:
from openpyxl import load_workbook

wb = load_workbook(OUTPUT_FILE)

print(wb.sheetnames)

['01_Master_Dataset', '02_Descriptive_Statistics', '03_Pearson_Correlation', '04_Mann_Kendall_Test', '05_Trend_Summary']

In [24]:
print(annual_df.head())

   Year  Sea Ice Area (Million km²)  Ocean Mean Albedo  Sea Ice Deviation (%)  \
0  2000                      10.303             0.4890               7.163631
1  2001                      10.462             0.4980               8.817423
2  2002                      10.103             0.4835               5.083390
3  2003                      10.244             0.4770               6.549960
4  2004                      10.073             0.4933               4.771353

   Albedo Deviation (%)
0              6.834052
1              8.800323
2              5.632442
3              4.212357
4              7.773492

In [27]:
print(methodology_df.head())

                          Step  \
0       Sea Ice Long-Term Mean
1  Ocean Albedo Long-Term Mean
2            Sea Ice Deviation
3             Albedo Deviation
4          Pearson Correlation

                                         Description
0      Average of yearly mean sea ice from 2000-2025
1  Average of yearly ocean mean albedo from 2000-...
2  (Yearly Mean - Long-Term Mean)/Long-Term Mean ...
3  (Ocean Mean Albedo - Long-Term Mean)/Long-Term...
4  Measures linear relationship between sea ice a...

In [25]:
# ========================================================
# Sheet 6
# ========================================================

annual_df.to_excel(
    writer,
    sheet_name="06_Annual_Statistics",
    index=False
)

# ========================================================
# Sheet 7
# ========================================================

methodology_df.to_excel(
    writer,
    sheet_name="07_Methodology",
    index=False
)

# ========================================================
# Sheet 8
# ========================================================

metadata_df.to_excel(
    writer,
    sheet_name="08_Metadata",
    index=False
)

In [26]:
from openpyxl import load_workbook

wb = load_workbook(OUTPUT_FILE)

print(wb.sheetnames)

['01_Master_Dataset', '02_Descriptive_Statistics', '03_Pearson_Correlation', '04_Mann_Kendall_Test', '05_Trend_Summary']

In [28]:
from openpyxl import load_workbook

wb = load_workbook(OUTPUT_FILE)

print("Before :", wb.sheetnames)

with pd.ExcelWriter(
    OUTPUT_FILE,
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:

    annual_df.to_excel(
        writer,
        sheet_name="06_Annual_Statistics",
        index=False
    )

    methodology_df.to_excel(
        writer,
        sheet_name="07_Methodology",
        index=False
    )

    metadata_df.to_excel(
        writer,
        sheet_name="08_Metadata",
        index=False
    )

wb = load_workbook(OUTPUT_FILE)

print("After :", wb.sheetnames)

Before : ['01_Master_Dataset', '02_Descriptive_Statistics', '03_Pearson_Correlation', '04_Mann_Kendall_Test', '05_Trend_Summary']

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ACER\\OneDrive\\Desktop\\ISRO\\snow_2\\Results\\Arctic_SeaIce_Albedo_Trend_Analysis_2000_2025.xlsx'

In [29]:
import os

print(os.path.exists(OUTPUT_FILE))
print(os.path.abspath(OUTPUT_FILE))

True
C:\Users\ACER\OneDrive\Desktop\ISRO\snow_2\Results\Arctic_SeaIce_Albedo_Trend_Analysis_2000_2025.xlsx

In [33]:
with pd.ExcelWriter(
    OUTPUT_FILE,
    engine="openpyxl"
) as writer:

    df.to_excel(...)
    descriptive_df.to_excel(...)
    correlation_df.to_excel(...)
    mk_df.to_excel(...)
    trend_df.to_excel(...)
    annual_df.to_excel(...)
    methodology_df.to_excel(...)
    metadata_df.to_excel(...)

IndexError: At least one sheet must be visible

In [34]:
OUTPUT_FILE = os.path.join(
    RESULTS,
    "Arctic_SeaIce_Albedo_Trend_Analysis_2000_2025.xlsx"
)

with pd.ExcelWriter(OUTPUT_FILE, engine="openpyxl") as writer:

    df.to_excel(
        writer,
        sheet_name="01_Master_Dataset",
        index=False
    )

    descriptive_df.to_excel(
        writer,
        sheet_name="02_Descriptive_Statistics",
        index=False
    )

    correlation_df.to_excel(
        writer,
        sheet_name="03_Pearson_Correlation",
        index=False
    )

    mk_df.to_excel(
        writer,
        sheet_name="04_Mann_Kendall_Test",
        index=False
    )

    trend_df.to_excel(
        writer,
        sheet_name="05_Trend_Summary",
        index=False
    )

    annual_df.to_excel(
        writer,
        sheet_name="06_Annual_Statistics",
        index=False
    )

    methodology_df.to_excel(
        writer,
        sheet_name="07_Methodology",
        index=False
    )

    metadata_df.to_excel(
        writer,
        sheet_name="08_Metadata",
        index=False
    )

print("Workbook Saved Successfully!")
print(OUTPUT_FILE)

Workbook Saved Successfully!
C:\Users\ACER\OneDrive\Desktop\ISRO\snow_2\Results\Arctic_SeaIce_Albedo_Trend_Analysis_2000_2025.xlsx

In [35]:
[
'01_Master_Dataset',
'02_Descriptive_Statistics',
'03_Pearson_Correlation',
'04_Mann_Kendall_Test',
'05_Trend_Summary',
'06_Annual_Statistics',
'07_Methodology',
'08_Metadata'
]

['01_Master_Dataset',
 '02_Descriptive_Statistics',
 '03_Pearson_Correlation',
 '04_Mann_Kendall_Test',
 '05_Trend_Summary',
 '06_Annual_Statistics',
 '07_Methodology',
 '08_Metadata']